2020-08-04 16:49:28.259 | INFO     | hagworm.extend.asyncio.base:__init__:72 - 
 __  __   ______   ______   __     __   ______   ______   __    __
/\ \_\ \ /\  __ \ /\  ___\ /\ \  _ \ \ /\  __ \ /\  == \ /\ "-./  \
\ \  __ \\ \  __ \\ \ \__ \\ \ \/ ".\ \\ \ \/\ \\ \  __< \ \ \-./\ \
 \ \_\ \_\\ \_\ \_\\ \_____\\ \__/".~\_\\ \_____\\ \_\ \_\\ \_\ \ \_\
  \/_/\/_/ \/_/\/_/ \/_____/ \/_/   \/_/ \/_____/ \/_/ /_/ \/_/  \/_/
hagworm 3.10.1
python 3.7.8 (v3.7.8:4b47a5b6ba, Jun 27 2020, 04:47:50) 
[Clang 6.0 (clang-600.0.57)]
system Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
2020-08-04 16:49:28.265 | SUCCESS  | hagworm.extend.asyncio.base:install_uvloop:30 - uvloop 0.14.0 installed
2020-08-04 16:49:28.267 | SUCCESS  | hagworm.extend.asyncio.base:run:93 - Start process no.0
2020-08-04 16:49:28.963 | INFO     | hagworm.extend.asyncio.net:send_request:175 - POST http://dev.jiayouxueba.cn:8080/api/member/external/teacher/signin => status:200
2020-08-04 16:49:28.967 | INFO     | __main__:parse:72 - The response is success, resp is {'status': 200, 'headers': {'Server': 'nginx/1.15.6', 'Date': 'Tue, 04 Aug 2020 08:49:28 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip'}, 'body': b'{"success":false,"code":104,"msg":"\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7\xe5\x92\x8c\xe5\xaf\x86\xe7\xa0\x81\xe4\xb8\x8d\xe5\x8c\xb9\xe9\x85\x8d"}'}
2020-08-04 16:49:28.969 | ERROR    | hagworm.extend.base:__exit__:965 - 'bytes' object has no attribute 'get'
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/frame/stress_tests.py", line 74, in _func
    await func(*args, **kwargs)
          │     │       └ {}
          │     └ (1, 1)
          └ <bound method Runner.run of <hagworm.frame.stress_tests.Runner object at 0x7fe0187773d0>>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/frame/stress_tests.py", line 185, in run
    await tasks
          └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7fe01bb71110>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/extend/asyncio/base.py", line 447, in __await__
    yield from asyncio.gather(*self._task_list).__await__()
               │       │       │    └ [<Task finished coro=<Task.run() done, defined at /Users/liangyi/Project/git/python/first/com/Stresstest/login.py:85> excepti...
               │       │       └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7fe01bb71110>
               │       └ <function gather at 0x7fe019e27200>
               └ <module 'asyncio' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/__init__.py'>

  File "/Users/liangyi/Project/git/python/first/com/Stresstest/login.py", line 94, in run
    await tasks
          └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7fe01bba1a90>

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/extend/asyncio/base.py", line 447, in __await__
    yield from asyncio.gather(*self._task_list).__await__()
               │       │       │    └ [<Task finished coro=<Task.parse() done, defined at /Users/liangyi/Project/git/python/first/com/Stresstest/login.py:44> excep...
               │       │       └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7fe01bba1a90>
               │       └ <function gather at 0x7fe019e27200>
               └ <module 'asyncio' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/__init__.py'>

  File "/Users/liangyi/Project/git/python/first/com/Stresstest/login.py", line 74, in parse
    request_msg=resp.body.get('msg', None)
                │    └ <property object at 0x7fe01ba70e30>
                └ {'status': 200, 'headers': {'Server': 'nginx/1.15.6', 'Date': 'Tue, 04 Aug 2020 08:49:28 GMT', 'Content-Type': 'application/j...

AttributeError: 'bytes' object has no attribute 'get'
2020-08-04 16:49:28.984 | SUCCESS  | hagworm.extend.asyncio.base:run:97 - Stop process no.0
