2020-08-05 09:50:54.348 | INFO     | hagworm.extend.asyncio.base:__init__:72 - 
 __  __   ______   ______   __     __   ______   ______   __    __
/\ \_\ \ /\  __ \ /\  ___\ /\ \  _ \ \ /\  __ \ /\  == \ /\ "-./  \
\ \  __ \\ \  __ \\ \ \__ \\ \ \/ ".\ \\ \ \/\ \\ \  __< \ \ \-./\ \
 \ \_\ \_\\ \_\ \_\\ \_____\\ \__/".~\_\\ \_____\\ \_\ \_\\ \_\ \ \_\
  \/_/\/_/ \/_/\/_/ \/_____/ \/_/   \/_/ \/_____/ \/_/ /_/ \/_/  \/_/
hagworm 3.10.1
python 3.7.8 (v3.7.8:4b47a5b6ba, Jun 27 2020, 04:47:50) 
[Clang 6.0 (clang-600.0.57)]
system Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
2020-08-05 09:50:54.354 | SUCCESS  | hagworm.extend.asyncio.base:install_uvloop:30 - uvloop 0.14.0 installed
2020-08-05 09:50:54.355 | SUCCESS  | hagworm.extend.asyncio.base:run:93 - Start process no.0
2020-08-05 09:50:57.914 | ERROR    | __main__:parse:59 - The response of server is fail, Exception is 404, message='Not Found', url=URL('http://dev.jiayouxueba.com/down')
2020-08-05 09:50:57.918 | ERROR    | __main__:parse:59 - The response of server is fail, Exception is 404, message='Not Found', url=URL('http://dev.jiayouxueba.com/down')
2020-08-05 09:50:59.926 | INFO     | hagworm.frame.stress_tests:_func:75 - 
|  EventName  |  SuccessTotal  |  FailureTotal  |  SuccessRatio  |  SuccessAveTime  |  SuccessMinTime  |  SuccessMaxTime  |
|-------------|----------------|----------------|----------------|------------------|------------------|------------------|
|  Request    |  0             |  2             |  0.00%         |  0.000s          |  0.000s          |  0.000s          |

2020-08-05 09:50:59.927 | SUCCESS  | hagworm.extend.asyncio.base:run:97 - Stop process no.0
