2020-08-05 09:58:19.151 | INFO     | hagworm.extend.asyncio.base:__init__:72 - 
 __  __   ______   ______   __     __   ______   ______   __    __
/\ \_\ \ /\  __ \ /\  ___\ /\ \  _ \ \ /\  __ \ /\  == \ /\ "-./  \
\ \  __ \\ \  __ \\ \ \__ \\ \ \/ ".\ \\ \ \/\ \\ \  __< \ \ \-./\ \
 \ \_\ \_\\ \_\ \_\\ \_____\\ \__/".~\_\\ \_____\\ \_\ \_\\ \_\ \ \_\
  \/_/\/_/ \/_/\/_/ \/_____/ \/_/   \/_/ \/_____/ \/_/ /_/ \/_/  \/_/
hagworm 3.10.1
python 3.7.8 (v3.7.8:4b47a5b6ba, Jun 27 2020, 04:47:50) 
[Clang 6.0 (clang-600.0.57)]
system Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
2020-08-05 09:58:19.157 | SUCCESS  | hagworm.extend.asyncio.base:install_uvloop:30 - uvloop 0.14.0 installed
2020-08-05 09:58:19.159 | SUCCESS  | hagworm.extend.asyncio.base:run:93 - Start process no.0
2020-08-05 09:58:22.340 | INFO     | hagworm.extend.asyncio.net:send_request:175 - GET http://dev.jiayouxueba.com/down => status:200
2020-08-05 09:58:22.346 | ERROR    | hagworm.extend.base:__exit__:965 - 'bytes' object has no attribute 'status'
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/frame/stress_tests.py", line 74, in _func
    await func(*args, **kwargs)
          │     │       └ {}
          │     └ (1, 1)
          └ <bound method Runner.run of <hagworm.frame.stress_tests.Runner object at 0x7fc5d60773d0>>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/frame/stress_tests.py", line 185, in run
    await tasks
          └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7fc5da56b350>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/extend/asyncio/base.py", line 447, in __await__
    yield from asyncio.gather(*self._task_list).__await__()
               │       │       │    └ [<Task finished coro=<Task.run() done, defined at /Users/liangyi/Project/git/python/first/com/Stresstest/url.py:78> exception...
               │       │       └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7fc5da56b350>
               │       └ <function gather at 0x7fc5d9128290>
               └ <module 'asyncio' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/__init__.py'>

  File "/Users/liangyi/Project/git/python/first/com/Stresstest/url.py", line 87, in run
    await tasks
          └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7fc5da598ad0>

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hagworm/extend/asyncio/base.py", line 447, in __await__
    yield from asyncio.gather(*self._task_list).__await__()
               │       │       │    └ [<Task finished coro=<Task.parse() done, defined at /Users/liangyi/Project/git/python/first/com/Stresstest/url.py:40> excepti...
               │       │       └ <hagworm.extend.asyncio.base.MultiTasks object at 0x7fc5da598ad0>
               │       └ <function gather at 0x7fc5d9128290>
               └ <module 'asyncio' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/__init__.py'>

  File "/Users/liangyi/Project/git/python/first/com/Stresstest/url.py", line 65, in parse
    if resp and resp.status == 200:
       │        └ b'<!DOCTYPE html><html lang="zh-CN"><head><link rel="icon" href="/static/favicon.ico" type="image/x-icon"/><link rel="shortcu...
       └ b'<!DOCTYPE html><html lang="zh-CN"><head><link rel="icon" href="/static/favicon.ico" type="image/x-icon"/><link rel="shortcu...

AttributeError: 'bytes' object has no attribute 'status'
2020-08-05 09:58:22.360 | INFO     | hagworm.extend.asyncio.net:send_request:175 - GET http://dev.jiayouxueba.com/down => status:200
2020-08-05 09:58:22.363 | SUCCESS  | hagworm.extend.asyncio.base:run:97 - Stop process no.0
